version: '2'
services:
        test:
                build: test
                depends_on:
                        - tomcat
                links:
                        - tomcat
                        - mysql
                volumes:
                        - ./test/output:/tmp/output
                environment:
                        - DOCKER=true
                env_file: env_file
